
enum State {
    SP= "São Paulo",
    RJ= "Rio de Janeiro",
    MG= "Minas Gerais",
    PE= "Pernambuco",
    BA= "Bahia",
    SC= "Santa Catarina",
    RS= "Rio Grande do Sul",
    PR= "Paraná",
    CE= "Ceará",
    PI= "Piauí",
    GO= "Gaoiás",
    MT= "Mato Grosso",
    PA= "Pará",
    AM= "Amazonas",
    AP= "Amapá",
    AL= "Alagoas",
    PB= "Paraíba",
    RO= "Rondônia",
    RR= "Raraima",
    RN= "Rio Grande do Norte",
    ES= "Espirito Santo",
    DF= "Distrito Federal",
    AC= "Acre",
    MA= "Maranhão",
    SE= "Sergipe",
    TO= "Tocantins",
    MS= "Mato Grosso do Sul"
}