INSERT INTO APPOINTMENT_TYPE(DESCRIPTION, ICON) VALUES('Vacina','stethoscope');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION, ICON) VALUES('Consulta','clinic-medical');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION, ICON) VALUES('Passeio','dog-leashed');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION, ICON) VALUES('Banho/Tosa','shower');