INSERT INTO APPOINTMENT_TYPE(DESCRIPTION) VALUES('Vacina');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION) VALUES('Consulta');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION) VALUES('Passeio');
INSERT INTO APPOINTMENT_TYPE(DESCRIPTION) VALUES('Banho/Tosa');