INSERT INTO pet_type (description, icon) VALUES ('Cão', 'dog');
INSERT INTO pet_type (description, icon) VALUES ('Gato', 'cat');
INSERT INTO pet_type (description, icon) VALUES ('Pássaro', 'dove');
INSERT INTO pet_type (description, icon) VALUES ('Peixe', 'fish');
INSERT INTO pet_type (description, icon) VALUES ('Outro', 'paw');

INSERT INTO breed (description, pet_type_id) VALUES ('Affenpinscher', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Afghan Hound', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Airedale Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Akita', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('American Bully', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('American Foxhound', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('American Pit Bull Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('American Staffordshire Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Basset Hound', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Beagle', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bichon Frisé', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bioadeiro Australiano', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Border Collie', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Boston Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Boxer', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Buldogue Francês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Buldogue Inglês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bull Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Cane Corso', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Cavalier King Charles Spaniel', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Chihuahua', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Chow Chow', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Cocker Spaniel Inglês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Dachshund', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Dálmata', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Doberman', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Dogo Argentino', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Dogue Alemão', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Fila Brasileiro', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Golden Retriever', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Husky Siberiano', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Jack Russel Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Labrador Retriever', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Lhasa Apso', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Lulu da Pomerânia', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Maltês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Mastiff Inglês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Mastim Tibetano', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pastor Alemão', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pastor Australiano', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pastor de Shetland', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pequinês', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pinscher Miniatura', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Poodle', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Pug', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Rottweiler', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Schnauzer', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Shar-Pei', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Shiba', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Shi Tzu', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Stafffordshire Bull Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Vira-Lata', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Weimara', (SELECT id FROM pet_type WHERE description = 'Cão') );
INSERT INTO breed (description, pet_type_id) VALUES ('Yorkshire Terrier', (SELECT id FROM pet_type WHERE description = 'Cão') );



INSERT INTO breed (description, pet_type_id) VALUES ('Azul Russo', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Persa', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Scott Fold', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Maine Coon', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Siamês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Ragdoll', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato de Pelo Curto Inglês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Munchkin', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Sphynx', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Norueguês da Floresta', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato Abissíno', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Angorá', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato de Bengala', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Sagrado da Birmânia', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato Birmanês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Curl Americano', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Himalaio', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato Savannah', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Exótico', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Mau Egípsio', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bombaim', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato Manês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato de Pelo Curto Americano', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Toyger', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Cornish Rex', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Siberiano', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Nebelung', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Singapura', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Devon Rex', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('American Wirehair', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Balinês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Chartreux', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('LaPerm', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Ragamuffin', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Korat', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bobtail Japonês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Oriental Shorthair', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Oriental Havana', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Bobtail Americano', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Gato de Pelo Curto Brasileiro', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Snowshoe', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Somali', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Selkirk Rex', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Turkish Van', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Tonquinês', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Donskoy', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Persa Tradicional', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Burmilla', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Minskin', (SELECT id FROM pet_type WHERE description = 'Gato') );
INSERT INTO breed (description, pet_type_id) VALUES ('Likoi', (SELECT id FROM pet_type WHERE description = 'Gato') );
	

